const express = require('express');
const router = express.Router();
const db = require('../services/database');
const llmService = require('../utils/llmService');

router.post('/generate', async (req, res) => {
  try {
    const { mood, trackCount = 5 } = req.body;
    
    if (!mood || typeof mood !== 'string') {
      return res.status(400).json({ 
        success: false, 
        error: 'Mood description is required' 
      });
    }

    const tracks = await db.getTracks();
    
    if (tracks.length < 3) {
      return res.status(400).json({
        success: false,
        error: 'Need at least 3 tracks to generate a playlist'
      });
    }

    const llmResult = await llmService.generatePlaylist(tracks, mood, trackCount);

    const playlist = await db.createPlaylist(
      `${mood} Mix`,
      mood,
      llmResult.reasoning || 'Generated by AI'
    );

    const playlistItems = [];
    for (const item of llmResult.tracks) {
      try {
        await db.addTrackToPlaylist(
          playlist.id,
          item.trackId,
          item.weight,
          item.order
        );
        playlistItems.push(item);
      } catch (error) {
        console.error('Failed to add track:', error.message);
      }
    }

    res.json({
      success: true,
      message: 'Playlist generated successfully',
      data: {
        playlistId: playlist.id,
        mood,
        tracks: playlistItems,
        reasoning: llmResult.reasoning
      }
    });

  } catch (error) {
    console.error('Generate playlist error:', error);
    res.status(500).json({ 
      success: false,
      error: error.message || 'Failed to generate playlist'
    });
  }
});

router.get('/stats/top-tracks', async (req, res) => {
  try {
    const limit = parseInt(req.query.limit) || 10;
    const topTracks = await db.getTopTracks(limit);
    
    res.json({
      success: true,
      data: topTracks
    });
  } catch (error) {
    console.error('Get top tracks error:', error);
    res.status(500).json({ 
      success: false,
      error: error.message 
    });
  }
});

router.get('/:id', async (req, res) => {
  try {
    const playlist = await db.getPlaylistWithTracks(req.params.id);
    
    if (!playlist) {
      return res.status(404).json({ 
        success: false,
        error: 'Playlist not found' 
      });
    }

    res.json({
      success: true,
      data: playlist
    });
  } catch (error) {
    console.error('Get playlist error:', error);
    res.status(500).json({ 
      success: false,
      error: error.message 
    });
  }
});

router.get('/health/db', async (req, res) => {
  try {
    const health = await db.healthCheck();
    res.json({
      success: true,
      ...health,
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      status: 'unhealthy',
      error: error.message
    });
  }
});

module.exports = router;